### PR TITLE
Upgrade roslaunch to noetic

### PR DESCRIPTION
**Pull request by travisariggs**
Add the ability to query the param server from roslaunch in noetic.  The first commit is cherry-picked from our kinetic-based fork of upstream's ros-comm.  We have more changes we would like to migrate, but this is the first.

In addition, to get things to work with snapcraft, I removed all of the python 2 package conditional dependencies from this branch of ros-comm.

---
This change is [Reviewable](https://reviewable.io/reviews/badgertechnologies/ros_comm/10)

### CODE REVIEW

**Review by dandedrick — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/ros_comm/10)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @travisariggs)

___
*[clients/rospy/package.xml, line 41 at r2](https://reviewable.io/reviews/badgertechnologies/ros_comm/10#-Mcp-D3cDJgq-zP5tv0p:-Mcp-D3cDJgq-zP5tv0q:byjhjj8) ([raw file](https://github.com/badgertechnologies/ros_comm/blob/f5fa3a168760d62e9693f10dcb9adfffc6132d22/clients/rospy/package.xml#L41)):*
> ```XML
> 
>   <exec_depend>genpy</exec_depend>
>   <exec_depend condition="$ROS_PYTHON_VERSION == 2">python-numpy</exec_depend>
> ```

I have a quick fix that I think should prevent us from having to make this modification. I'm going to just run some quick tests and then I'll push a branch for consideration. This may be something we have to deal with in multiple places in the future so I'd rather fix it up at a snapcraft level than have to modify every package that we pull in that happens to use this syntax.

**Review by travisariggs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/ros_comm/10)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @dandedrick)

___
*[clients/rospy/package.xml, line 41 at r2](https://reviewable.io/reviews/badgertechnologies/ros_comm/10#-Mcp-D3cDJgq-zP5tv0p:-McpBYEM7aoQ6OeoSr0y:bqicb05) ([raw file](https://github.com/badgertechnologies/ros_comm/blob/f5fa3a168760d62e9693f10dcb9adfffc6132d22/clients/rospy/package.xml#L41)):*
<details><summary><i>Previously, dandedrick (Dan Dedrick) wrote…</i></summary><blockquote>

I have a quick fix that I think should prevent us from having to make this modification. I'm going to just run some quick tests and then I'll push a branch for consideration. This may be something we have to deal with in multiple places in the future so I'd rather fix it up at a snapcraft level than have to modify every package that we pull in that happens to use this syntax.
</blockquote></details>

I'm fine with that.  Do you think we can get that in quickly?  We are trying to get this in before the first cut of 1.21 on Monday.

**Review by dandedrick — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/ros_comm/10)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @travisariggs)

___
*[clients/rospy/package.xml, line 41 at r2](https://reviewable.io/reviews/badgertechnologies/ros_comm/10#-Mcp-D3cDJgq-zP5tv0p:-McpJ_6HCf4IfdacNpH0:b-6r41ll) ([raw file](https://github.com/badgertechnologies/ros_comm/blob/f5fa3a168760d62e9693f10dcb9adfffc6132d22/clients/rospy/package.xml#L41)):*
<details><summary><i>Previously, travisariggs (Travis Riggs) wrote…</i></summary><blockquote>

I'm fine with that.  Do you think we can get that in quickly?  We are trying to get this in before the first cut of 1.21 on Monday.
</blockquote></details>

https://github.com/BadgerTechnologies/bar_truck/pull/2049 allows snapcraft to evaluate conditions instead of including all dpendencies regardless of condition.

**Review by travisariggs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/ros_comm/10)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dandedrick)

___
*[clients/rospy/package.xml, line 41 at r2](https://reviewable.io/reviews/badgertechnologies/ros_comm/10#-Mcp-D3cDJgq-zP5tv0p:-MczYOEpC4APG6GgVvfF:b-qebyk8) ([raw file](https://github.com/badgertechnologies/ros_comm/blob/f5fa3a168760d62e9693f10dcb9adfffc6132d22/clients/rospy/package.xml#L41)):*
<details><summary><i>Previously, dandedrick (Dan Dedrick) wrote…</i></summary><blockquote>

https://github.com/BadgerTechnologies/bar_truck/pull/2049 allows snapcraft to evaluate conditions instead of including all dpendencies regardless of condition.
</blockquote></details>

I dropped my second commit that removed all of the conditional dependencies and will instead rely on your patches to snapcraft to handle those.

**Review by travisariggs — COMMENTED** [review]
> Dismissed @dandedrick from a discussion.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/ros_comm/10)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @travisariggs)

**Comment by c-andy-martin** [comment]
:+1:

**Review by c-andy-martin — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/ros_comm/10#-:-MczoByE5Z1v7HuAh3sz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @travisariggs)

**Pull request merged**
