### PR TITLE
rospy: Fix severe bug in get_param_cached()

### PR DESCRIPTION
**Pull request by howardcochran**
This bug is severe because it can break ordinary rospy.get_param()
after a rospy.get_param_cached() has been perfomed. And, furthermore,
rospy.log*() does a rospy.get_param_cached()!

When a parameter is set in the cache, the cached value will always be
returned, even when the caller uses ordinary rospy.get_param(). This is
as designed, as subscribeParam() is done to make the cache
receive updates from the param server whenever the value changes.

However, existing code only uses the presence of a key in the cache to
indicate whether the cached param is valid. However, this is not enough.

Suppose the param server has these contents:
    top1:
        min: 1
        max: 10

    print(rospy.get_param('/top'))
    # So far, so good. Output is:
    # {'min': 1, 'max': 10}

    print(rospy.get_param_cached('/top/min'))
    # As expected, this outputs:
    # 1
    # However, ***'s cache now contains:
    # {'top': {'min': 1}}
    # This is correct, because only the value of 'min' is cached.

    print(rospy.get_param('/top'))
    # Incorrect output:
    # {'top': {'min': 1}}
    # Because ****'s cache makes it look like /top is in the cache, but
    # it was never actually cached.

The fix is to track the actual keys that are cached in a set. Upon, only
return a cached value if either the key or a parent of it is in the set.

This was found by productioncode which attempts to get all params using
rospy.get_param('/'). This works OK as long as no calls to
rospy.get_param_cached() have been made. However, the rospy.log*()
functions all do
rospy.get_param_cached('rosout_disable_topics_generation'). So after the
first loginfo, subsequent calls to rospy.get_param('/') only the single
cached key rather than all params.

Fixes: d16296acb755 ("rospy: added get_param_cached (#1515)")

---
This change is [Reviewable](https://reviewable.io/reviews/badgertechnologies/ros_comm/15)

### CODE REVIEW

**Review by c-andy-martin — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/ros_comm/15)* status: all files reviewed, 7 unresolved discussions (waiting on @howardcochran)

___
*[-- commits, line 17 at r1](https://reviewable.io/reviews/badgertechnologies/ros_comm/15#-MpCDQBW4Js1v7hUlpDe):*
extra `1`
___
*[-- commits, line 28 at r1](https://reviewable.io/reviews/badgertechnologies/ros_comm/15#-MpCDTRP5og-G8FI8JL-):*
fix `***`
___
*[-- commits, line 35 at r1](https://reviewable.io/reviews/badgertechnologies/ros_comm/15#-MpCDVUq1hyXKQpaYsyU):*
fix `****`
___
*[-- commits, line 38 at r1](https://reviewable.io/reviews/badgertechnologies/ros_comm/15#-MpCDZ4jAD4Lq9oShjFl):*
fix `... Upon, only`
___
*[-- commits, line 41 at r1](https://reviewable.io/reviews/badgertechnologies/ros_comm/15#-MpCDXb_6Ti6RT8Skz3A):*
fix `productioncode`
___
*[clients/rospy/src/rospy/impl/paramserver.py, line 172 at r1](https://reviewable.io/reviews/badgertechnologies/ros_comm/15#-MpCD-Q52Z4aX_hRn-DA:-MpCD-Q52Z4aX_hRn-DB:b-cdtut3) ([raw file](https://github.com/badgertechnologies/ros_comm/blob/37214f30c86dcaf014ec21a81842f391f17ed773/clients/rospy/src/rospy/impl/paramserver.py#L172)):*
> ```Python
>                 raise KeyError(key)
>             val = self.d
>             if key == GLOBALNS:
> ```

I would remove this entire check, as your loop correctly handles namespaces being empty.
___
*[clients/rospy/src/rospy/impl/paramserver.py, line 182 at r1](https://reviewable.io/reviews/badgertechnologies/ros_comm/15#-MpCGaoK8Mu-eBBHQc50:-MpCGaoL50rTJRBwbvTl:b-1rur8s) ([raw file](https://github.com/badgertechnologies/ros_comm/blob/37214f30c86dcaf014ec21a81842f391f17ed773/clients/rospy/src/rospy/impl/paramserver.py#L182)):*
> ```Python
>                 # so that updates are subscribed.
>                 is_subscribed = False
>                 for i in range(len(namespaces), 0, -1):
> ```

It seems to me if you are checking the non-global namespace and the global namespace is subscribed this check still fails, as it doesn't check an empty slice of namespaces below, even though we would get updates on the parameter. Also, there is no need to loop backwards, you could just loop from `range(0, len(namespaces)+1`

**Comment by c-andy-martin** [comment]
___
*[clients/rospy/src/rospy/impl/paramserver.py, line 172 at r1](https://reviewable.io/reviews/badgertechnologies/ros_comm/15#-MpCD-Q52Z4aX_hRn-DA:-MpCIcIk9e3-Hsy0pekY:bnh03ts) ([raw file](https://github.com/badgertechnologies/ros_comm/blob/37214f30c86dcaf014ec21a81842f391f17ed773/clients/rospy/src/rospy/impl/paramserver.py#L172)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I would remove this entire check, as your loop correctly handles namespaces being empty.
</blockquote></details>

actually, if you remove this you will make merging harder b/c it would move a whole block in. I'm fine with how it is then

**Review by howardcochran — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/ros_comm/15)* status: all files reviewed, 7 unresolved discussions (waiting on @c-andy-martin)

___
*[-- commits, line 17 at r1](https://reviewable.io/reviews/badgertechnologies/ros_comm/15#-MpCDQBW4Js1v7hUlpDe):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

extra `1`
</blockquote></details>

Done.
___
*[-- commits, line 28 at r1](https://reviewable.io/reviews/badgertechnologies/ros_comm/15#-MpCDTRP5og-G8FI8JL-):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

fix `***`
</blockquote></details>

Done.
___
*[-- commits, line 35 at r1](https://reviewable.io/reviews/badgertechnologies/ros_comm/15#-MpCDVUq1hyXKQpaYsyU):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

fix `****`
</blockquote></details>

Done.
___
*[-- commits, line 38 at r1](https://reviewable.io/reviews/badgertechnologies/ros_comm/15#-MpCDZ4jAD4Lq9oShjFl):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

fix `... Upon, only`
</blockquote></details>

Done.
___
*[-- commits, line 41 at r1](https://reviewable.io/reviews/badgertechnologies/ros_comm/15#-MpCDXb_6Ti6RT8Skz3A):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

fix `productioncode`
</blockquote></details>

Done.
___
*[clients/rospy/src/rospy/impl/paramserver.py, line 172 at r1](https://reviewable.io/reviews/badgertechnologies/ros_comm/15#-MpCD-Q52Z4aX_hRn-DA:-MpCJTVY3u08McEz90gu:b9qfw0) ([raw file](https://github.com/badgertechnologies/ros_comm/blob/37214f30c86dcaf014ec21a81842f391f17ed773/clients/rospy/src/rospy/impl/paramserver.py#L172)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

actually, if you remove this you will make merging harder b/c it would move a whole block in. I'm fine with how it is then
</blockquote></details>

Yeah, I think I'll leave it be.
___
*[clients/rospy/src/rospy/impl/paramserver.py, line 182 at r1](https://reviewable.io/reviews/badgertechnologies/ros_comm/15#-MpCGaoK8Mu-eBBHQc50:-MpCJehT8_sRIisfkeOe:b-751hc3) ([raw file](https://github.com/badgertechnologies/ros_comm/blob/37214f30c86dcaf014ec21a81842f391f17ed773/clients/rospy/src/rospy/impl/paramserver.py#L182)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

It seems to me if you are checking the non-global namespace and the global namespace is subscribed this check still fails, as it doesn't check an empty slice of namespaces below, even though we would get updates on the parameter. Also, there is no need to loop backwards, you could just loop from `range(0, len(namespaces)+1`
</blockquote></details>

Looping backwards is a tiny attempt to be more performant, thinking that the more specific parameter is more likely to get a hit than a parent/grandparent.

**Comment by howardcochran** [comment]
___
*[clients/rospy/src/rospy/impl/paramserver.py, line 182 at r1](https://reviewable.io/reviews/badgertechnologies/ros_comm/15#-MpCGaoK8Mu-eBBHQc50:-MpDDmF68GWK_0femrR6:b80lddv) ([raw file](https://github.com/badgertechnologies/ros_comm/blob/37214f30c86dcaf014ec21a81842f391f17ed773/clients/rospy/src/rospy/impl/paramserver.py#L182)):*
<details><summary><i>Previously, howardcochran (Howard Cochran) wrote…</i></summary><blockquote>

Looping backwards is a tiny attempt to be more performant, thinking that the more specific parameter is more likely to get a hit than a parent/grandparent.
</blockquote></details>

I reproduced and fixed the problem of not getting cache hits when the GLOBALNS Is subscribed.

**Review by c-andy-martin — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/ros_comm/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @howardcochran)

**Review by c-andy-martin — APPROVED** [review]
:lgtm: Thanks for figuring this out and creating an elegant fix!

> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/ros_comm/15#-:-MpDbiMkBABaKO4ApMrE:b5zpnxz)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @howardcochran)

**Pull request merged**
